---
- name: Install metricbeat on remote machine
  hosts: webservers 
  become: true
  tasks:
   - name: Download metricbeat
     command: sudo curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

   - name: Installing metricbeat
     command: sudo dpkg -i metricbeat-7.6.1-amd64.deb
    
   - name: Copying metricbeat config file
     copy:
       src: /etc/ansible/metricbeat-config.yml
       dest: /etc/metricbeat/metricbeat.yml
   - name: Enable docker module
     command: sudo metricbeat modules enable docker

   - name: setup metric beat
     command: sudo metricbeat setup

   - name: Start metricbeat service
     command: sudo service metricbeat start

#   - name: Monitoring 
#     command: sudo metricbeat -e

   - name: Start metricbeat on boot
     systemd:
        name: metricbeat
        enabled: yes